/**
 * Implement Gatsby's SSR (Server Side Rendering) APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/ssr-apis/
 */

import React from 'react';

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="preload-sfmono-medium"
      rel="preload"
      as="font"
      href="/fonts/SFMono/SFMono-Medium.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-sfmono-medium-italic"
      rel="preload"
      as="font"
      href="/fonts/SFMono/SFMono-MediumItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-sfmono-regular"
      rel="preload"
      as="font"
      href="/fonts/SFMono/SFMono-Regular.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-sfmono-regular-italic"
      rel="preload"
      as="font"
      href="/fonts/SFMono/SFMono-RegularItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-sfmono-semibold"
      rel="preload"
      as="font"
      href="/fonts/SFMono/SFMono-Semibold.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-sfmono-semibold-italic"
      rel="preload"
      as="font"
      href="/fonts/SFMono/SFMono-SemiboldItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-light"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-Light.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-light-italic"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-LightItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-medium"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-Medium.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-medium-italic"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-MediumItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-regular"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-Regular.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-regular-italic"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-RegularItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-semibold"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-Semibold.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="preload-calibre-semibold-italic"
      rel="preload"
      as="font"
      href="/fonts/Calibre/Calibre-SemiboldItalic.woff2"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
  ]);
};
