[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9.13"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"
    Netlify-CDN-Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"
    Netlify-CDN-Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"