[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9.13"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*"
  [headers.values]
    Netlify-CDN-Cache-Control = "public, s-maxage=0, must-revalidate"
    Cache-Control = "public, max-age=0, must-revalidate"